"""
Utility functions for loading completed (dense) depth maps for sparse datasets.

Datasets supported:
- ETH3D: ground_truth_depth_completed/
- Waymo: depth_completed/

These completed depth maps are generated by scripts/depth_completion.py using
IP-Basic + Guided Filter algorithm.
"""

import os
import numpy as np
import torch
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


def get_completed_depth_path(original_path: str, dataset_name: str) -> str:
    """
    Get the path to completed depth map based on original sparse depth path.

    Args:
        original_path: Path to the original sparse depth file
        dataset_name: Dataset name ('eth3d', 'waymo_seg')

    Returns:
        Path to completed depth map, or None if not applicable
    """
    original_path = Path(original_path)

    if dataset_name == 'eth3d':
        # ETH3D: ground_truth_depth/dslr_images/xxx.JPG -> ground_truth_depth_completed/dslr_images/xxx.JPG
        if 'ground_truth_depth' in str(original_path):
            completed_path = str(original_path).replace(
                'ground_truth_depth',
                'ground_truth_depth_completed'
            )
            return completed_path

    elif dataset_name == 'waymo_seg':
        # Waymo: FRONT/depth/xxxx.npy -> FRONT/depth_completed/xxxx.npy
        if '/depth/' in str(original_path):
            completed_path = str(original_path).replace('/depth/', '/depth_completed/')
            return completed_path

    return None


def has_completed_depth(original_path: str, dataset_name: str) -> bool:
    """
    Check if completed depth map exists for the given path.

    Args:
        original_path: Path to the original sparse depth file
        dataset_name: Dataset name ('eth3d', 'waymo_seg')

    Returns:
        True if completed depth map exists
    """
    completed_path = get_completed_depth_path(original_path, dataset_name)
    if completed_path is None:
        return False
    return os.path.exists(completed_path)


def load_completed_depth_eth3d(completed_path: str, target_size: tuple = None) -> torch.Tensor:
    """
    Load completed ETH3D depth map.

    The completed depth is saved in the same format as original (binary float32),
    but dense instead of sparse.

    Args:
        completed_path: Path to completed depth file
        target_size: Optional (H, W) to resize to

    Returns:
        torch.Tensor: Depth in meters [H, W]
    """
    import cv2

    # ETH3D completed depth is stored as binary float32
    # The original resolution is 6048x4032, but we saved at original image resolution
    depth = np.fromfile(completed_path, dtype=np.float32)

    # Try to determine the dimensions
    # First try 6048x4032 (ETH3D default)
    if depth.size == 6048 * 4032:
        depth = depth.reshape((4032, 6048))
    elif depth.size == 8064 * 3024:
        # Alternative ETH3D resolution
        depth = depth.reshape((3024, 8064))
    else:
        # Try to find dimensions that work
        total = depth.size
        # Common ETH3D image dimensions
        possible_dims = [
            (4135, 6205),  # courtyard
            (4135, 6208),  # delivery_area
            (4130, 6201),  # facade
            (4032, 6048),  # default
            (3024, 8064),  # alternative
        ]
        found = False
        for h, w in possible_dims:
            if total == h * w:
                depth = depth.reshape((h, w))
                found = True
                break

        if not found:
            # Try to find matching dimensions
            sqrt_approx = int(np.sqrt(total))
            for h in range(sqrt_approx - 500, sqrt_approx + 500):
                if total % h == 0:
                    w = total // h
                    if 1.3 < w / h < 2.0:  # Reasonable aspect ratio
                        depth = depth.reshape((h, w))
                        found = True
                        break

            if not found:
                raise ValueError(f"Cannot determine dimensions for depth size {total}")

    # Handle infinity values (mark as 0 for invalid)
    depth = np.where(np.isinf(depth), 0, depth)

    # Resize if needed
    if target_size is not None:
        target_h, target_w = target_size
        if depth.shape != (target_h, target_w):
            depth = cv2.resize(depth, (target_w, target_h), interpolation=cv2.INTER_LINEAR)

    return torch.from_numpy(depth).float()


def load_completed_depth_waymo(completed_path: str, target_size: tuple = None) -> torch.Tensor:
    """
    Load completed Waymo depth map.

    The completed depth is saved as dense .npy (H, W) float32.
    -1 indicates no LiDAR coverage (above lidar_y_min).

    Args:
        completed_path: Path to completed depth file
        target_size: Optional (H, W) to resize to

    Returns:
        torch.Tensor: Depth in meters [H, W], -1 = no LiDAR coverage
    """
    import cv2

    depth = np.load(completed_path)  # [H, W] dense float32

    # Resize if needed
    if target_size is not None:
        target_h, target_w = target_size
        if depth.shape != (target_h, target_w):
            # For Waymo, need to handle -1 values carefully
            # Create mask for -1 values
            no_lidar_mask = depth < 0

            # Resize depth (set -1 to 0 temporarily for interpolation)
            depth_for_resize = np.where(no_lidar_mask, 0, depth)
            depth_resized = cv2.resize(depth_for_resize, (target_w, target_h),
                                        interpolation=cv2.INTER_LINEAR)

            # Resize mask
            no_lidar_resized = cv2.resize(
                no_lidar_mask.astype(np.float32),
                (target_w, target_h),
                interpolation=cv2.INTER_NEAREST
            ) > 0.5

            # Restore -1 values
            depth = np.where(no_lidar_resized, -1.0, depth_resized)

    return torch.from_numpy(depth).float()


def load_completed_depth(original_path: str, dataset_name: str,
                         target_size: tuple = None) -> torch.Tensor:
    """
    Load completed depth map for visualization purposes.

    Args:
        original_path: Path to original sparse depth file
        dataset_name: Dataset name ('eth3d', 'waymo_seg')
        target_size: Optional (H, W) to resize to

    Returns:
        torch.Tensor: Completed depth [H, W], or None if not available
    """
    completed_path = get_completed_depth_path(original_path, dataset_name)

    if completed_path is None or not os.path.exists(completed_path):
        logger.debug(f"Completed depth not found for {original_path}")
        return None

    try:
        if dataset_name == 'eth3d':
            return load_completed_depth_eth3d(completed_path, target_size)
        elif dataset_name == 'waymo_seg':
            return load_completed_depth_waymo(completed_path, target_size)
        else:
            logger.warning(f"Unknown dataset for completed depth: {dataset_name}")
            return None
    except Exception as e:
        logger.warning(f"Failed to load completed depth {completed_path}: {e}")
        return None


def depth_to_colormap(depth: np.ndarray, vmin: float = None, vmax: float = None,
                      no_lidar_color: tuple = (0, 0, 0)) -> np.ndarray:
    """
    Convert depth map to colormap visualization.

    Handles -1 values (no LiDAR coverage) as black.

    Args:
        depth: Depth map [H, W] in meters
        vmin: Minimum depth for colormap normalization
        vmax: Maximum depth for colormap normalization
        no_lidar_color: RGB color for -1 regions (default: black)

    Returns:
        np.ndarray: RGB colormap [H, W, 3] uint8
    """
    import matplotlib.pyplot as plt

    # Create mask for invalid regions
    no_lidar_mask = depth < 0
    valid_mask = (depth > 0) & np.isfinite(depth)

    # Auto-compute range from valid values
    if vmin is None and valid_mask.any():
        vmin = np.percentile(depth[valid_mask], 2)
    if vmax is None and valid_mask.any():
        vmax = np.percentile(depth[valid_mask], 98)

    if vmin is None:
        vmin = 0
    if vmax is None:
        vmax = 1

    # Normalize depth
    depth_normalized = np.clip((depth - vmin) / (vmax - vmin + 1e-8), 0, 1)

    # Apply colormap
    cmap = plt.cm.turbo
    colored = cmap(depth_normalized)[:, :, :3]  # RGB only, no alpha
    colored = (colored * 255).astype(np.uint8)

    # Set no-LiDAR regions to specified color
    colored[no_lidar_mask] = no_lidar_color

    # Set invalid regions (0 depth) to dark gray
    zero_mask = (depth == 0) & ~no_lidar_mask
    colored[zero_mask] = (30, 30, 30)

    return colored
